@startuml
class Bag{
    int _maxContentsNum
    block[] _blockContents = new block[_maxContentsNum]
    Dictionary _summaryContents

    list getContents()
    void inItem(block)
    block outItem()
    bool haveItem()
    void summaryToBlock()
    Dictionary getSummary()

}
class block{
    item _item = new item()
    int _num
    int _max

    block(item it, int num){}

    getBlock(){ return _item, _num}

    addNum() 
    subNum()
    maxNum()
    zeroNum()
}