@startuml
folder Model{
    folder object{
        class Status{
            int HP
            Vecter3 position
            
            void setHP()
            int getHP()
            ...
        }


    }
}