@startuml


interface ActionObject{
    event action
    fire()#イベント発行
}



class ActionEvent{
    ActionObject RecognizePlayerFront()#プレイヤーの前に何があるかを返す
    PlayerFrontObject = RecognizePlayerFront()
    PlayerFrontObject.fire()
}

Folder Action{
class Cook{
    list knowRecip()
    list CanMakeRecip(){getBagContent()}
    void Cook()#料理後バッグがいっぱいだとクラフト市内
}
class Craft{
    #現在レベルの取得
    #持ち物の取得
    #現在レベルに対するデータの取得
}
}
Folder getJson{
class item{}

}

Cook --> bag
ActionEvent --> Cook
ActionEvent --> Craft
Craft --> bag
Action --> getJson
