Folder getJson{

interface IAction{
    Use()
}


class ItemDataArray
{
  Item[] gameItems;
}

class JsonReaderFromResourcesFolder
{
   ItemDataArray GetItemDataArray ()
}

class Item {
    + string imgFileName
    + string name
    + string description
    + string id
    void Use()
}

class EatItem 
{
    //リンゴや木の実
    //music SE 
    int heal_amount 

}

class CraftItem
{
    // 斧など
    + Sozai[] sozai 
}

class CookItem
{
    // 料理
    + Sozai[] sozai 
}

class Sozai
{
    + string id 
    + int num 
}
}

class Ono{
    int Lv
    int useHP
    int atk

}
class PlayerStatus{
    int HP
    Ono ono
}


Item --u|> IAction

CraftItem <|-- Ono

EatItem --up|>Item
CraftItem ---up|>Item
CookItem --up|>EatItem
CookItem --u> Sozai
CraftItem --u>Sozai


